const mongoose=require("mongoose");
const UserSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true,
    },
    lastName:{
        type:String,
        required:true,
        trim:true,
    },
    email:{
        type:String,
        required:true,
        trim:true,
    },
    password:{
        type:String,
        required:true,

    },
    ContactNumber:{
        type:Number,
        required:true,

    },
    accountType:{
        type:String,
        enum:["Admin","Student","Instructor"],
        required:true,
    },
    Active:{
        type:Boolean,
        require:true,
    },
    Approve:{
        type:Boolean,
        require:true,
    },
    image:{
        type:String,
        required:true,
    },
    token:{
        type:String,

    },
    resetPasswordExpires:{
        type:Date,
    },
    Course:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Course",
    },
    additionalDetails:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Profile",
    },
    CourseProgram:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"CourseProgram",
    },
})
module.exports=mongoose.model("User",UserSchema);